CREATE DATABASE edupoll;

USE DATABASE edupoll;

CREATE TABLE student(
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL,
    firstName VARCHAR(256) NOT NULL,
    lastName VARCHAR(256) NOT NULL,
    email VARCHAR(256) NOT NULL,
    PRIMARY KEY (username),
)

CREATE TABLE teacher(
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL,
    firstName VARCHAR(256) NOT NULL,
    email VARCHAR(256) NOT NULL,
    school VARCHAR(256) NOT NULL,
    PRIMARY KEY (username)
)

CREATE TABLE class(
    cname VARCHAR(256) NOT NULL,
    teacher VARCHAR(256) NOT NUll,
    school VARCHAR(256) NOT NULL,
    PRIMARY KEY(cname),
    PRIMARY KEY(school),
    FOREIGN KEY(teacher) REFERENCES teacher(username)
)
CREATE TABLE sclass(
    username VARCHAR(256) NOT NULL,
    cname VARCHAR(256) NOT NULL,
    school VARCHAR(256) NOT NULL,
    grade INT NOT NULL DEFAULT 0,
    FOREIGN KEY(username) REFERENCES student(username) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(cname) REFERENCES class(cname) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(school) REFERENCES class(school) ON UPDATE CASCADE ON DELETE CASCADE
)
CREATE TABLE quiz(
    qname VARCHAR(256) NOT NULL,
    cname VARCHAR(256) NOT NULL,
    school VARCHAR(256) NOT NULL,
    PRIMARY KEY(qname),
    FOREIGN KEY(cname) REFERENCES class(cname) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(school) REFERENCES class(school) ON UPDATE CASCADE ON DELETE CASCADE
)
CREATE TABLE question(
    qid INT NOT NULL DEFAULT 0 AUTO_INCREMENT,
    content VARCHAR(256) NOT NULL,
    qImage VARCHAR(256) DEFAULT NULL,
    qname VARCHAR(256) NOT NULL,
    optionA VARCHAR(256) NOT NULL,
    optionB VARCHAR(256) NOT NULL,
    optionC VARCHAR(256) NOT NULL,
    optionD VARCHAR(256) NOT NULL,
    answer ENUM('A', 'B', 'C', 'D') NOT NULL,
    PRIMARY KEY(qid),
    FOREIGN KEY(qname) REFERENCES quiz(qname) ON UPDATE CASCADE ON DELETE CASCADE
)
